# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/PYNQ-Z2_v1.0.xdc

# Block Designs: bd/Keypad_encoder/Keypad_encoder.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Keypad_encoder || ORIG_REF_NAME==Keypad_encoder} -quiet] -quiet

# IP: bd/Keypad_encoder/ip/Keypad_encoder_counter_keypad_0_0/Keypad_encoder_counter_keypad_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Keypad_encoder_counter_keypad_0_0 || ORIG_REF_NAME==Keypad_encoder_counter_keypad_0_0} -quiet] -quiet

# IP: bd/Keypad_encoder/ip/Keypad_encoder_decoder_keypad_0_0/Keypad_encoder_decoder_keypad_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Keypad_encoder_decoder_keypad_0_0 || ORIG_REF_NAME==Keypad_encoder_decoder_keypad_0_0} -quiet] -quiet

# IP: bd/Keypad_encoder/ip/Keypad_encoder_mux_keypad_0_0/Keypad_encoder_mux_keypad_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Keypad_encoder_mux_keypad_0_0 || ORIG_REF_NAME==Keypad_encoder_mux_keypad_0_0} -quiet] -quiet

# IP: bd/Keypad_encoder/ip/Keypad_encoder_not_gate_keypad_0_0/Keypad_encoder_not_gate_keypad_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Keypad_encoder_not_gate_keypad_0_0 || ORIG_REF_NAME==Keypad_encoder_not_gate_keypad_0_0} -quiet] -quiet

# IP: bd/Keypad_encoder/ip/Keypad_encoder_clockdivider_0_0/Keypad_encoder_clockdivider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Keypad_encoder_clockdivider_0_0 || ORIG_REF_NAME==Keypad_encoder_clockdivider_0_0} -quiet] -quiet

# IP: bd/Keypad_encoder/ip/Keypad_encoder_mask_keypad_0_0/Keypad_encoder_mask_keypad_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Keypad_encoder_mask_keypad_0_0 || ORIG_REF_NAME==Keypad_encoder_mask_keypad_0_0} -quiet] -quiet

# XDC: C:/Users/jacob/Keypad_driver/Keypad_driver.gen/sources_1/bd/Keypad_encoder/Keypad_encoder_ooc.xdc
